from graphe import Station

quinconces: Station = Station(1, "quinconces", {"3": "0"}, True, [])
mairie: Station = Station(2, "mairie", {"3": "0"}, False, [])
republique: Station = Station(3, "republique", {"3": "0"}, False, [])
eglise: Station = Station(4, "eglise", {"3": "2"}, False, [])
issac: Station = Station(5, "issac", {"3": "2"}, True, [])
zola: Station = Station(6, "zola", {"3": "1"}, False, [])
lycee: Station = Station(7, "lycee", {"3": "1", "84": "0"}, False, [])
villepreux: Station = Station(8, "villepreux", {"3": "1"}, True, [])
proust: Station = Station(9, "proust", {"84": "0"}, True, [])
cantinole: Station = Station(10, "cantinole", {"84": "0"}, False, [])
aulnes: Station = Station(11, "aulnes", {"84": "2"}, False, [])
rostand: Station = Station(12, "rostand", {"84": "2"}, True, [])
cinq_chemins: Station = Station(13, "5 chemins", {"84": "1"}, False, [])
aeroport: Station = Station(14, "aeroport", {"84": "1"}, True, [])

quinconces.voisins.append((mairie, 2))
mairie.voisins.append((quinconces, 2))
mairie.voisins.append((republique, 3))
republique.voisins.append((mairie, 3))
republique.voisins.append((eglise, 2))
republique.voisins.append((zola, 1))
eglise.voisins.append((republique, 3))
eglise.voisins.append((issac, 1))
issac.voisins.append((eglise, 1))
zola.voisins.append((republique, 1))
zola.voisins.append((lycee, 2))
lycee.voisins.append((zola, 2))
lycee.voisins.append((villepreux, 2))
lycee.voisins.append((proust, 1))
lycee.voisins.append((cantinole, 1))
villepreux.voisins.append((lycee, 2))
proust.voisins.append((lycee, 1))
cantinole.voisins.append((lycee, 1))
cantinole.voisins.append((aulnes, 3))
cantinole.voisins.append((cinq_chemins, 3))
aulnes.voisins.append((cantinole, 3))
aulnes.voisins.append((rostand, 2))
rostand.voisins.append((aulnes, 2))
cinq_chemins.voisins.append((cantinole, 3))
cinq_chemins.voisins.append((aeroport, 2))
aeroport.voisins.append((cinq_chemins, 2))

all_stations = [quinconces, mairie, republique, eglise, issac, zola, lycee, villepreux, proust,
                cantinole, aulnes, rostand, cinq_chemins, aeroport]